### ISSUE TITLE
add contributing guide

### ISSUE THREAD

**Issue by kachun333** [kachun333/OurPromise#36]
just in case there are enthusiast who like to contribute

**Comment by aswin2108** [comment]
I would like to work on this, can you assign me the issue?

**Comment by kachun333** [comment]
> I would like to work on this, can you assign me the issue?

Sure, that would be a great help.

**Comment by aswin2108** [comment]
@kachun333  I have started my work on it.
When I tried to set up a local env, it showed errors.
I did `npm install` and then did `npm start` and the following showed up:
![image](https://user-images.githubusercontent.com/72661784/208628808-0f0f2978-671c-4c7d-9f29-93f30dea6ec2.png)
Some more are there like this.

**Comment by kachun333** [comment]
Hi @aswin2108 , can you try to pull the latest master, I have resolved all Typescript & ESLint errors (but not ESLint warning yet)

A successful `npm start` will have the following messages in the terminal ⬇️ 
```logs
Compiled with warnings.

[eslint]
src\components\pages\GraduateDetails.tsx
  Line 122:9:  Unexpected console statement  no-console

src\components\pages\Lecturers.tsx 
  Line 160:9:  Unexpected console statement  no-console

src\components\pages\auth\Create.tsx
  Line 92:5:  Unexpected alert  no-alert
xt-line to the line before.

WARNING in [eslint]
src\components\pages\GraduateDetails.tsx
  Line 122:9:  Unexpected console statement  no-console

src\components\pages\Lecturers.tsx
  Line 160:9:  Unexpected console statement  no-console

src\components\pages\auth\Create.tsx
  Line 92:5:  Unexpected alert  no-alert

src\components\pages\auth\Login.tsx  Line 123:5:  Unexpected alert  no-alert

src\components\pages\graduates\Graduates.tsx
  Line 150:9:  Unexpected console statement  no-console

webpack compiled with 1 warning
No issues found.
```

after the compilation succeeds, open `http://localhost:3000/` in your browser manually. You will see this ⬇️ (sorry the image src link is broken)
![image](https://user-images.githubusercontent.com/34387770/208661843-d3e12219-9c43-4752-b575-acc47fb28415.png)

> Note: There are a lot of things that are broken, they will be fixed accordingly

> Note 2: Avoid navigating to `/graduates` and `/lecturers`, they are highly inefficient and consume too much resources on the cloud. I will fix them ASAP

**Comment by aswin2108** [comment]
@kachun333 Its perfectly working for me.
Is there any IRS channel or something for this project?

**Comment by kachun333** [comment]
> @kachun333 Its perfectly working for me.
> Is there any IRS channel or something for this project?

@aswin2108 what is IRS channel?

**Comment by aswin2108** [comment]
@kachun333 I meant the IRC channel. Typo mistake! Sry!

**Comment by kachun333** [comment]
No worries @aswin2108 , we didn't have any chat-based communication method.

Do you think it's necessary? probably we can use discord?

**Comment by aswin2108** [comment]
@kachun333 No it's not necessary at the moment! Create it when the community grows and you feel more communication is needed!
For the time being, we can skip it.
Yeah, discord works! Generally, people use slack and others but have seen discords too!
In the end, we need to communicate that's all!
So for now I am not including it, fine right?

**Comment by kachun333** [comment]
yup, it's fine. Thanks, @aswin2108
