### ISSUE TITLE
Use Next Gen Image Formats 

### ISSUE THREAD

**Issue by kachun333** [kachun333/OurPromise#8]
images in `/assets` folder should use next-gen image format to help users save their mobile data usage

can consider using the `WebP` image format

A balance between small image size and high image quality
- image size should not be more than 200KB
- Image should look good on a 1920x1080 monitor

**Comment by kachun333** [comment]
@aswin2108 are you interested to contribute by working on this issue?

**Comment by aswin2108** [comment]
@kachun333 Yeah I would love to! But never worked with a similar one! So if you could tell me what to do with this, I would surely give it a try!

**Comment by aswin2108** [comment]
@kachun333 So what do you think?If you can give me the topic or resources, I will handle the rest!

**Comment by kachun333** [comment]
hi @aswin2108 

### Motivation
the file size of the images in [/assets/images](https://github.com/kachun333/OurPromise/tree/master/src/assets/images) directory is too big. Many are larger than 1 MB. The app will consume too much of users mobile data if the app resources is so big.

So we need to compress the image. With a balance between small image size and high image quality

- image size should not be more than 200KB (e.g. original jpg image size 1.5MB -> compressed webp image size 198KB)
- Image should look good on a 1920x1080 monitor

### What to do
Would be glad if you can help to compress all images in `assets/images` (and convert them to WebP image format) using any tool of your choice. 
You may find [this list of online tools](https://github.com/bradtraversy/design-resources-for-developers#image-compression) helpful.
A bulk conversion tool might be your best friend.

After conversion/compression is done, replace them in the directory. 
e.g. `assets/images/graduates.jpg` -> `assets/images/graduates.webp` // compressed & converted
// do this for all images in the directory

Open a PR

**Comment by aswin2108** [comment]
@kachun333 Will do it!

**Comment by aswin2108** [comment]
@kachun333 have checked out some tools. The thing I observed is that when an image is of size greater than 2.5Mb conversion can be done in 2 ways:
* Do direct conversion 2.2Mb the image looks good. Then I tried to reduce the image size to less than 200kb. The maximum I can go is 223Kb. But in this case the image quality is not that good. I thought of attaching it, but when I did it both looked same. For understanding I would say 2.2Mb image looks perfect. 223Kb image when zoomed in the faces are all terrible.
* Second approach was to compress the image first and then convert it. In this case I was able to reduce the size to 1.2Mb with perfect quality. Maximmum I could reduce was up to 218Kb which had bad quality.  
Image took for conversion[/assets/images/banner/graduates.jpg](https://github.com/kachun333/OurPromise/tree/master/src/assets/images/banner/graduates.jpg)
By bad I mean this: This below image shows how the 223Kb and 218Kb looks like!  
![image](https://user-images.githubusercontent.com/72661784/209620626-7cb4ac2c-88ba-4da3-af96-e5d3fae8b774.png)

So what to do?
Can we increase the bar for such large files?

**Comment by kachun333** [comment]
@aswin2108 

interesting.

The current goal is to reduce mobile data usage. imagine the user just opens the app and 0.5GB of mobile data is gone. That's really bad. Users would usually just wanna scroll around and have a high-level overview of the app only. 

So, the 200+KB image size is acceptable, as well as the quality of the photo (after compression) is acceptable as well. 

In the future, we can have a feature that allows users to `click to view photo in high resolution`. In that case, users can zoom in or download the photo (that is larger than 1MB)

**Comment by aswin2108** [comment]
@kachun333 You are absolutely right! The last-mentioned idea would surely work!
